---
- name: Update system and reboot if needed
  hosts: all
  become: yes
  tasks:

    - name: Update all packages to the latest version
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes

    - name: Reboot the host
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible after package update"
        pre_reboot_delay: 10
        post_reboot_delay: 30
        reboot_timeout: 600
