---
- name: Execute Change Automation on Target Host
  hosts: all
  gather_facts: true

  tasks:
    - name: Copy script to remote host
      ansible.builtin.copy:
        src: ./scripts/pfx_enroll_download.sh
        dest: /tmp/pfx_enroll_download.sh
        mode: '0700'

    - name: Run script on remote host
      ansible.builtin.shell: /tmp/pfx_enroll_download.sh
      environment:
        CHANGE_NUMBER: "{{ change_number }}"
        CN_NAME: "{{ cn_name }}"
        CA_NAME: "{{ ca_name }}"
        PASSWORD: "{{ password }}"
      register: result
      failed_when: result.rc != 0
      no_log: false  # Turn back to true later if password is exposed

    - name: Print script output on success
      debug:
        msg: "{{ result.stdout_lines }}"
      when: result.rc == 0

    - name: Print script output on failure
      debug:
        msg: "{{ result.stdout_lines }}"
      when: result.rc != 0
