---
- name: Download script on Ansible control node (proxy used here)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure scripts directory exists on control node
      ansible.builtin.file:
        path: ./scripts
        state: directory
        mode: '0755'

    - name: Download script using HTTPS proxy on control node
      ansible.builtin.get_url:
        url: "https://example.com/path/to/pfx_enroll_download.sh"
        dest: "./scripts/pfx_enroll_download.sh"
        mode: '0700'
      environment:
        https_proxy: "http://192.168.30.1:8080"
        http_proxy: "http://192.168.30.1:8080"
        no_proxy: "localhost,127.0.0.1"

- name: Copy and run downloaded script on target hosts (no proxy used)
  hosts: all
  gather_facts: yes
  vars:
    remote_script_path: /tmp/pfx_enroll_download.sh

  tasks:
    - name: Copy script to remote host
      ansible.builtin.copy:
        src: ./scripts/pfx_enroll_download.sh
        dest: "{{ remote_script_path }}"
        mode: '0700'

    - name: Run script on remote host
      ansible.builtin.shell: "{{ remote_script_path }}"
      environment:
        CHANGE_NUMBER: "{{ change_number }}"
        CN_NAME: "{{ cn_name }}"
        CA_NAME: "{{ ca_name }}"
        PASSWORD: "{{ password }}"
      register: result
      failed_when: result.rc != 0
      no_log: false

    - name: Print script output on success
      debug:
        msg: "{{ result.stdout_lines }}"
      when: result.rc == 0

    - name: Print script output on failure
      debug:
        msg: "{{ result.stdout_lines }}"
      when: result.rc != 0

    - name: Remove script after execution
      ansible.builtin.file:
        path: "{{ remote_script_path }}"
        state: absent
      ignore_errors: yes
