---
- name: VMware VM Control
  hosts: all
  connection: local

  tasks:

    - name: Display VM action
      ansible.builtin.debug:
        msg:
          - "VM: {{ inventory_hostname }}"
          - "Action: {{ vm_action }}"
          - "Path: {{ vmx_path }}"

    - name: Execute VMware action
      ansible.builtin.command:
        cmd: >
          "/mnt/c/Program Files (x86)/VMware/VMware Workstation/vmrun.exe"
          {{ vm_action }}
          "{{ vmx_path }}"
