---
- name: VMware VM Control
  hosts: wsl-control
  become: false

  tasks:

    - name: Execute VMware action
      ansible.builtin.command:
        cmd: >
          "/mnt/c/Program Files (x86)/VMware/VMware Workstation/vmrun.exe"
          {{ vm_action }}
          "D:\Virtual Machines\{{ target_vm }}.com\{{ target_vm }}.com.vmx"
